// Factory-registered window manifests. `npm run window:sync` and
// `npm run window:scaffold` insert NEW windows into this file (above the
// sync anchor) so adding a window never grows a hand-curated file. When this
// file approaches its size budget, graduate stable entries into a category
// file under src/lib/manifest/ — the composed WINDOW_MANIFESTS is order-safe.
// Pure data: no logic lives here.

export const FACTORY_WINDOW_MANIFESTS = [
  {
    kind: 'module',
    canvasType: 'module',
    label: 'Module',
    componentName: 'ModuleWindow',
    componentPath: 'src/components/ModuleWindow.jsx',
    defaultSize: { w: 440, h: 520 },
    header: { title: 'Module', icon: 'Toolbox' },
    moduleMenu: { show: false }, // opened from a request, a template or My modules, never blank
    lab: { title: 'Module', props: { title: 'Tip calculator', status: 'building', request: 'a tip calculator for my crew' } },
  },
  {
    kind: 'leads',
    canvasType: 'leads',
    label: 'Lead Queue',
    componentName: 'LeadsWindow',
    componentPath: 'src/components/LeadsWindow.jsx',
    defaultSize: { w: 380, h: 520 },
    launcher: { show: true, order: 45, icon: 'Group', label: 'Lead queue', hint: 'Search & Rescue pipeline' },
    lab: { title: 'Lead Queue' },
  },
  {
    kind: 'leadHound',
    canvasType: 'leadHound',
    label: 'LeadHound',
    componentName: 'LeadHoundWindow',
    componentPath: 'src/components/LeadHoundWindow.jsx',
    defaultSize: { w: 820, h: 600 },
    moduleMenu: { show: true, order: 46, icon: 'Search', label: 'LeadHound', hint: 'Find leads and draft a 7-day intro sequence' },
    launcher: { show: true, order: 46, icon: 'Search', label: 'LeadHound', hint: 'find leads with Tavily' },
    lab: { title: 'LeadHound' },
  },
  {
    kind: 'marketplace',
    canvasType: 'marketplace',
    label: 'Marketplace',
    componentName: 'MarketplaceWindow',
    componentPath: 'src/components/MarketplaceWindow.jsx',
    defaultSize: { w: 720, h: 520 },
    header: { title: 'Marketplace', icon: 'ShoppingBag' },
    moduleMenu: { show: true, order: 5, icon: 'ShoppingBag', label: 'Marketplace', hint: 'Toggle which windows appear on your canvas' },
    launcher: { show: true, startHere: true, startHereOrder: 40, order: 16, icon: 'ShoppingBag', label: 'Browse modules', hint: 'add reviewed capabilities' },
  },
  {
    kind: 'registry',
    canvasType: 'registry',
    label: 'Agent Registry',
    componentName: 'RegistryWindow',
    componentPath: 'src/components/RegistryWindow.jsx',
    defaultSize: { w: 800, h: 560 },
    moduleMenu: { show: true, order: 10, icon: 'Plug', label: 'Agent Registry', hint: 'Browse, install, publish agents' },
    launcher: { show: true, order: 15, icon: 'Plug', label: 'Agent Registry', hint: 'review agents and add-ons' },
  },
  {
    kind: 'helloFactory',
    canvasType: 'helloFactory',
    label: 'Hello Factory',
    componentName: 'HelloFactoryWindow',
    componentPath: 'src/components/windows/helloFactory/index.jsx',
    defaultSize: { w: 440, h: 300 },
    moduleMenu: { show: false, status: 'coming-soon' },
    lab: {"title":"Hello Factory","props":{"note":"This window was added by creating one folder and running window:sync."}},
  },
  {
    kind: 'policyDashboard',
    canvasType: 'policyDashboard',
    label: 'Action Approvals',
    componentName: 'PolicyDashboardWindow',
    componentPath: 'src/components/PolicyDashboardWindow.jsx',
    defaultSize: { w: 520, h: 360 },
    moduleMenu: { show: true, order: 18, icon: 'Alert', label: 'Action Approvals', hint: 'Review agent-requested write actions' },
    launcher: { show: true, order: 18, icon: 'Alert', label: 'Action Approvals', hint: 'review agent-requested writes' },
    lab: { title: 'Action Approvals' },
  },
  {
    kind: 'governance',
    canvasType: 'governance',
    label: 'Governance',
    componentName: 'GovernanceWindow',
    componentPath: 'src/components/GovernanceWindow.jsx',
    defaultSize: { w: 900, h: 600 },
    moduleMenu: { show: false, status: 'coming-soon' },
    lab: { title: 'Governance' },
  },
  {
    kind: 'reliability',
    canvasType: 'reliability',
    label: 'Reliability',
    componentName: 'ReliabilityWindow',
    componentPath: 'src/components/ReliabilityWindow.jsx',
    defaultSize: { w: 800, h: 600 },
    moduleMenu: { show: true, order: 15, icon: 'Shield', label: 'Reliability', hint: 'AI Code Reliability Dashboard' },
    lab: { title: 'Reliability' },
  },
  {
    kind: 'ideaFoundry',
    canvasType: 'ideaFoundry',
    label: 'Idea Foundry',
    componentName: 'IdeaFoundryWindow',
    componentPath: 'src/components/IdeaFoundryWindow.jsx',
    defaultSize: { w: 1000, h: 800 },
    moduleMenu: { show: true, order: 22, icon: 'Flask', label: 'Idea Foundry', hint: 'Route idea cards' },
    launcher: { show: true, order: 42, icon: 'Flask', label: 'Idea Foundry', hint: 'route idea cards' },
    lab: { title: 'Idea Foundry' },
  },
  {
    kind: 'ollama',
    canvasType: 'ollama',
    label: 'Ollama',
    componentName: 'OllamaNodeWindow',
    componentPath: 'src/components/OllamaNodeWindow.jsx',
    defaultSize: { w: 600, h: 700 },
    moduleMenu: { show: true, order: 24, icon: 'Bot', label: 'Ollama', hint: 'Chat with local models' },
    launcher: { show: true, order: 44, icon: 'Bot', label: 'Ollama', hint: 'chat with local models' },
    lab: { title: 'Ollama' },
  },
  {
    kind: 'webviewShell',
    canvasType: 'webview',
    label: 'Webview Shell',
    componentName: 'WebviewShellWindow',
    componentPath: 'src/components/WebviewShellWindow.jsx',
    defaultSize: { w: 720, h: 560 },
    embedMode: 'webview',
    moduleMenu: { show: false, status: 'coming-soon' },
    lab: { title: 'Webview Shell' },
  },
  {
    kind: 'whatsapp',
    canvasType: 'whatsapp',
    label: 'WhatsApp',
    componentName: 'WhatsAppWindow',
    componentPath: 'src/components/WhatsAppWindow.jsx',
    defaultSize: { w: 420, h: 640 },
    embedMode: 'webview',
    moduleMenu: { show: true, order: 26, icon: 'Chat', label: 'WhatsApp', hint: 'Open WhatsApp Web or send a quick message' },
    launcher: { show: true, order: 46, icon: 'Chat', label: 'WhatsApp', hint: 'message via WhatsApp Web' },
    lab: { title: 'WhatsApp' },
  },
  {
    kind: 'agentConsole',
    canvasType: 'agentConsole',
    label: 'Agent Console',
    componentName: 'AgentConsoleWindow',
    componentPath: 'src/components/AgentConsoleWindow.jsx',
    defaultSize: { w: 640, h: 640 },
    modeAvailability: { cloud_saas: false },
    moduleMenu: { show: true, order: 19, icon: 'Terminal', label: 'Agent Console', hint: 'Claude Code, Codex and Gemini CLI as teammates' },
    launcher: { show: true, order: 59, icon: 'Terminal', label: 'Coding Agent', hint: 'Claude Code, Codex, Gemini CLI' },
    lab: { title: 'Agent Console' },
  },
  // window:sync inserts new windows above this line — do not remove.
];
